# Site
repository: UHeeJoon/uheejoon.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유희준
title: 백엔드 개발자
email: yhjyhj3855@gmail.com
website: https://codding-til-theory.tistory.com

darkmode: true

github_username:  UHeeJoon
instagram_username: u.heejoon
linkedin_username: 유희준


about_title: About Me
about_profile_image: images/tmp_profile.jpg
about_content: | 
  웹 서비스 백엔드 개발자로 성장하기 위해 Spring과 Java를 중심으로 깊이 있는 학습을 진행하고 있습니다. 
  특히, Java 기반의 백엔드 서비스 개발에 큰 흥미를 느끼며, 효율적인 시스템 아키텍처와 데이터 흐름을 설계하는 과정에서 보람을 느낍니다.

  개발을 시작한 이후 다양한 프로젝트를 경험하며, 기획부터 개발, 배포까지의 전반적인 과정을 직접 수행해 보았습니다. 
  그중에서도 백엔드 서비스 설계 및 구현이 가장 흥미로웠고, 이를 더 잘하기 위해 주도적으로 학습을 이어가고 있습니다. 
  특히, 데이터베이스 설계, API 개발, 서버 운영 등에 관심이 많으며, 비즈니스 로직을 최적화하고 확장 가능한 서비스를 구축하 것을 목표로 하고 있습니다.

# <p style="font-size: 24px; font-weight: bold; padding-block: 8px;">끊임없는 학습과 성장</p>

# 저는 문제를 해결하는 과정에서 배우는 즐거움을 무엇보다 중요하게 생각합니다. 
# 이를 위해 [백준](https://www.acmicpc.net/user/dbgmlwns)및 프로그래머스에서에서 알고리즘 문제를 풀며, 문제 해결력을 기르고 있습니다.
# 알고리즘을 학습하는 이유는 단순히 코딩 테스트를 준비하기 위해서가 아니라, 더 나은 코드 작성법과 효율적인 데이터 처리 기법을 익혀 실무에 적용하기 위해서입니다.

# 학교에서 배우는 내용만으로는 부족함을 느껴 방과 후에 방과 후 월요일부터 금요일까지 매일 4시간씩 학원을 다니며 추가적으로 학습을 이어갔습니다. 
# 학원에서는 Java, Spring, 데이터베이스 설계 등 실무와 밀접한 기술을 집중적으로 학습하며, 이를 개인 프로젝트나 팀 프로젝트에 적극적으로 적용 했습니다.

# <p style="font-size: 24px; font-weight: bold; padding-block: 8px;">개발자로서의 철학과 태도</p>

# 개발자로서 가장 중요한 덕목은 끊임없이 배우려는 태도와 문제를 해결하는 집요함이라고 생각합니다. 
# 기술은 빠르게 변화하며, 한 가지 기술만 익히는 것으로는 좋은 개발자가 될 수 없다고 생각합니다. 
# 따라서 저는 새로운 기술을 배우는 것을 자연스럽게 받아들이며, 더 나은 해결책을 찾기 위해 끊임없이 탐구합니다.

# 현재 저의 수준을 객관적으로 바라보면서 부족한 점을 스스로 인식하고, 이를 보완하기 위해 지속적으로 노력하는 것을 가장 중요하게 생각합니다. 
# 단순히 많은 기술을 나열하는 것이 아니라, 각 기술이 어떤 문제를 해결하기 위해 존재하는지 이해하고, 실무에서 효과적으로 적용할 수 있도록 깊이 있게 학습하는 것을 목표로 하고 있습니다.

# <p style="font-size: 24px; font-weight: bold; padding-block: 8px;">개발자로서의 철학과 태도</p>

# 앞으로는 더욱 견고한 백엔드 시스템을 설계하고, 대규모 트래픽을 효율적으로 처리할 수 있는 아키텍처에 대해 연구하고 싶습니다. 
# 특히 도메인 주도 설계(DDD)와 MSA(Microservices Architecture)에 대한 이해도를 높이고, 대용량 데이터를 효과적으로 처리할 수 있는 기술 스택을 익히는 것이 목표입니다. 
# 또한, CI/CD 및 클라우드 환경(AWS, Docker, Kubernetes 등)에 대한 실무 경험을 쌓아 백엔드 개발뿐만 아니라 서버 운영 및 배포까지 아우를 수 있는 개발자로 성장하고 싶습니다.

content:
  - title: 경력
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 모빌씨앤씨 인턴 
        caption: 2024.08 ~ 2025.02 (재직 중)
        description: |
          - 백엔드 개발자로서 사내 연수 과정 참여
          - 사내 프로젝트 개발

  - title: 기술
    layout: list
    content: 
      - layout: left
        title: Back-end
        description: |
          - Spring Boot, Spring MVC, Spring WebFlux
          - JPA/Hibernate, QueryDSL, MyBatis
          - Spring Cloud

      - layout: left
        title : DevOps
        description: |
          - MySQL, Oracle, MongoDB, Redis
          - AWS ECS, AWS RDS, Terraform, Vault
          - Docker, Message Queue(Kafka, RabbitMQ)

      - layout: left
        title : Front-end
        description: |
          - Next.js, Typescript, ES6, Ajax

      - layout: left
        title : Etc
        description: |
          - Golang, Rust, NestJS
          - git/github

  - title: 프로젝트
    layout: list
    content:
      - layout: left
        title: 모빌씨앤씨 설문 조사 서비스 개발
        caption: 2024.11 - 2024.12 (팀 프로젝트)
        sub_title: |
          사용 기술 : <br/>
          Spring Boot, JPA/Hibernate PostgreSQL, Spring Cloud(Config, Gateway, Eureka), <br/>
          OAuth2, JWT, Nginx, Redis(Cache, Pub/sub), Flyway, Docker 
        description: |
          - 관리자, 응답자, 설문 및 설문 응답 등 핵심 도메인 설계 및 서비스 구현 
          - Backend 리더로서 아키텍처 설계 및 개발 주도  
          - Nginx와 SSL을 활용한 보안 강화 및 서버 환경 구축  
          - Flyway를 활용한 DB 마이그레이션 자동화 및 버전 관리
          - Redis Pub/Sub + SSE Emitter 를 이용한 실시간 알림 생성

      - layout: left
        title: 한신대학교 전공 박람회 사전 예약 서비스
        caption: 2023.09.04 - 2023.09.10 (1인 개발)
        sub_title: |
          사용 기술 : <br/>
          Spring Boot, Spring Session, Mybatis, Thymeleaf, ES6, Ajax, Oracle, AWS EC2
        description: |
          - 학교에서 실제 서비스 할 사전 예약 사이트 제작 의뢰를 받아 1주일간 디자인부터 AWS에 배포까지 진행
          - 요구사항 분석 후 도메인 설계 및 데이터 모델링을 수행하고, 지속적인 피드백을 통해 서비스 안정성 확보
          - 서비스 운영을 위해 필요한 데이터를 학교 측과 협의하여 확보 후 개발 진행
          - Spring Session을 활용한 사용자 인증 처리

      - layout: left
        title: BodeumMe
        caption:  (팀 프로젝트)
        sub_title: |
          사용 기술 : <br/>
          Spring Boot, Oracle, Mybatis, Thymeleaf, HTML5/CSS3, ES6, Ajax, Gradle
        description: | 
          - 포스팅 기능을 맡아서 개발 (포스트 정렬 및 조회, 세부사항 확인)
          - UML 다이어그램 작성, 순서도 작성과 같은 설계단계부터 프로젝트를 진행
          - MyBatis와 DAO 패턴을 활용한 데이터 액세스 계층 구현
          - 게시물 검색 기능을 위한 동적 쿼리 설계 및 페이징 처리
          
      - layout: left
        title: 2호선 뭐먹지?
        caption: 2021.11.01 - 2021.11.05 (팀 프로젝트)
        additional_links:
          - title:  2호선 뭐먹지? (유튜브)
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=2StcVXOVi8I

        sub_title: |
          사용 기술 : <br/>
          Python, Jinja2, HTML5/CSS3, JavaScript, MongoDB, Robo3T, AWS
        description: | 
          - Python의 beautifulsoup을 사용해 크롤링한 데이터를 바탕으로 해당 역 주변의 식당 리스트를 가져오고 별점과 리뷰를 남길 수 있으며 직접 쓴 리뷰를 수정, 제거할 수 있는 마이페이지도 구현 또한 쿠키 세션기능을 활용해 로그아웃 기능을 구현
          - Domain과 AWS를 구매하여 실질적인 서비스가 가능하도록 배포
          - 이 프로젝트에서 전반적인 서비스 구현(크롤링 / 데이터 저장, 조회, 수정, 삭제/ 별점 남기기/ 페이지 렌더링)을 담당


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한신대학교
        caption: 2019.03 - 2025.02
        description: | # this will include new lines to allow paragraphs
          정보통신학부 졸업 예정 <br/>
          데이터베이스, 네트워크, 운영체제, 알고리즘 등 컴퓨터 공학의 핵심 이론 학습
      - layout: left
        title: 코리아IT아카데미아 웹개발 종합반
        caption: 2022.08 - 2023.01 | 2023.03 - 2023.08
        description: | # this will include new lines to allow paragraphs
          Java, HTML, JSP, Spring을 활용한 웹 개발 과정 및 전반적인 시스템 설계 이해 <br/>
          Spring Boot 및 RESTful API를 활용한 백엔드 서비스 개발 경험 축적 <br/>
          팀 프로젝트를 통해 요구사항 분석, 설계, 개발, 배포까지의 전 과정을 경험 <br/>


      - layout: left
        title: 코리아IT아카데미아 SQLD 자격증반
        caption: 2022.07
        description: | # this will include new lines to allow paragraphs
          [RDBMS(개인노션)](https://uheejoon.notion.site/DBMS-bd5e6d9d137b4dae98ef000d52bdae0a) <br/>
          학습 내용을 바탕으로 개인 노션을 통해 정리하며, 데이터베이스 설계 및 관리 역량 강화


      - layout: left
        title: 항해99
        caption: 2021.11
        description: | # this will include new lines to allow paragraphs
          Java, Spring Boot 기반 웹 애플리케이션 개발, API 설계 및 데이터 처리 방식 학습 <br/>
          웹 서버 구축, 크롤링, Spring MVC 패턴, Git 협업 등의 필수 개발 역량 습득 <br/>
          
footer_show_references: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
