# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유희준
title: 백엔드 개발자
email: yhjyhj3855@gmail.com
website: https://codding-til-theory.tistory.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  UHeeJoon
# stackoverflow_username: "00000001"  
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: u.heejoon
linkedin_username: 유희준
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 기술 블로그
  icon: fas fa-globe
  url: https://velog.io/@uheejoon

# About Section
about_title: About Me
about_profile_image: images/tmp_profile.jpg
about_content: | 
  웹 서비스 백엔드 개발자를 목표로 하여 Spring을 공부중인 학생입니다.
  가장 관심이 깊은 언어는 <mark>Java</mark>이며 Java를 활용한 서비스 개발을 희망하고 있습니다.
  지금까지 해본 개발 경험들 중에서는 백엔드 서비스를 구현하는 것에 가장 큰 재미를 느껴 주도적으로 공부를 해 나아가고 있습니다.

  평소에 취미로 [백준](https://www.acmicpc.net/user/dbgmlwns)이나 프로그래머스에서 코딩테스트 문제들을 매일매일 풀고 있으며 이를 토대로 백준 문제풀이 블로그를 운영하고 있습니다. 
  학교에서 하는 공부가 부족하다고 느껴 방과 후에 월 ~ 금 7시부터 10시까지 하는 학원을 꾸준히 다닐 정도로 배움에 대한 <mark>의욕이 강합</mark>니다.

  무언가를 해 나아가는 것에 있어서 <mark>배우려는 의지</mark>가 가장 중요하다고 생각합니다. 
  현재 저의 수준을 객관적으로 바라보면서 제게 부족한게 무엇인지 스스로 깨닫고 부족한 것을 메꾸기 위하여 배워 나가아가는 것에 집중하고 노력하고 있습니다.

content:
  - title: 경력
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 모빌씨앤씨 인턴
        sub_title: 2024.08 ~ 2025.02
        description: |
          - 인턴 연수
          - 사내 프로젝트 개발

  - title: 기술
    layout: list
    content: 
      - layout: left
        title: Back-end
        description: |
          - Spring MVC, Spring Boot, MyBatis, JPA
          - Spring Cloud, Resilience4j, gRPC
          - Spring Webflux

      - layout: left
        title : DevOps
        description: |
          - RDB, MongoDB, Redis
          - AWS ECS, Terraform
          - Docker, Message Queue

      - layout: left
        title : Front-end
        description: |
          - Next.js, Typescript
      - layout: left
        title : Etc
        description: |
          - Golang, Rust, NestJS
          - git/github

  - title: 프로젝트
    layout: list
    content:
      - layout: left
        title: BodeumMe <br/> (팀 프로젝트)
        sub_title: |
          사용 기술 : <br/>
          Spring boot, Oracle, Mybatis, Thymeleaf, HTML5/CSS3, JavaScript, Junit5, Gradle
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 후 수정 중...
          - 포스팅 기능을 맡아서 개발 (포스트 정렬 및 조회, 세부사항 확인)
          - UML 다이어그램 작성, 순서도 작성과 같은 설계단계부터 프로젝트를 진행
          - UI는 크몽이라는 사이트를 클론 코딩해서 사용
          
      - layout: left
        title: 2호선 뭐먹지? <br/> (팀 프로젝트)
        # link: https://www.youtube.com/watch?v=2StcVXOVi8I
        # link_text: Project Website
        additional_links:
          - title:  2호선 뭐먹지? (유튜브)
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=2StcVXOVi8I
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: |
          사용 기술 : <br/>
          Python, Jinja2, HTML5/CSS3, JavaScript, MongoDB, Robo3T, AWS
        description: | # this will include new lines to allow paragraphs
          - Python의 beautifulsoup을 사용해 크롤링한 데이터를 바탕으로 해당 역 주변의 식당 리스트를 가져오고 별점과 리뷰를 남길 수 있으며 직접 쓴 리뷰를 수정, 제거할 수 있는 마이페이지도 구현 또한 쿠키 세션기능을 활용해 로그아웃 기능을 구현
          - Domain과 AWS를 구매하여 실질적인 서비스가 가능하도록 배포
          - 이 프로젝트에서 전반적인 서비스 구현(크롤링 / 데이터 저장, 조회, 수정, 삭제/ 별점 남기기/ 페이지 렌더링)을 담당


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한신대학교
        caption: 2019.03 - 2025.02
        description: | # this will include new lines to allow paragraphs
          정보통신학부 졸업 예정

      - layout: left
        title: 코리아IT아카데미아 웹개발 종합반
        caption: 2022.08 - 2023.01
        description: | # this will include new lines to allow paragraphs
          Java, Html, Jsp, Spring을 통한 웹 개발과 개발 과정의 이해 <br/>
          Java, Spring, Spring Boot 순으로 배워 나아가면서 기술 스택이 성장하게 됨 <br/>


      - layout: left
        title: 코리아IT아카데미아 SQLD 자격증반
        caption: 2022.07
        description: | # this will include new lines to allow paragraphs
          [RDBMS(개인노션 #공부중)](https://uheejoon.notion.site/DBMS-bd5e6d9d137b4dae98ef000d52bdae0a) <br/>
          수업시간 때 배운것을 토대로 정리하며 RDBMS에대해 알게 됨


      - layout: left
        title: 항해99
        caption: 2021.10 - 2021.11
        description: | # this will include new lines to allow paragraphs
          자바와 스프링, 웹 서버, 크롤링, API, Spring MVC패턴, git/git hub등 개발자의 기본기들에 대해 배우게 되었고 <br/>
          어떤식으로 공부를 해야하고 내가 개발자로써 성장하기 위해 무엇을 해야하는지를 배우게된 그 무엇보다 값졌던 1달간의 짧은 여정
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
